postgresql-ha:
  commonAnnotations:
    ves.io/virtual-sites: "ha-services-ce/azure-ha-vs"

  clusterDomain: azure-ha.tme-lab-works-oeaclgke.tenant.local  
  kubeVersion: "v1.25.2"

  persistence:
    enabled: true
    size: 1Gi

  postgresql-ha:
    image:
      registry: ghcr.io
      repository: f5shemyakin/xchaazdemoguide/postgresql-repmgr
      tag: 15.1.0-debian-11-r0
    resources:
      requests:
        memory: 256Mi
        cpu: 5m
      limits:
        memory: 512Mi
        cpu: 1500m

    containerSecurityContext:
      runAsNonRoot: true

    replicaCount: 2
    username: haservices
    password: haservicespass    
    database: haservicesdb
    repmgrUsername: haservices
    repmgrPassword: haservicespass    
    repmgrDatabase: repmgrhaservicesdb

  pgpool:
    image:
      registry: ghcr.io
      repository: f5shemyakin/xchaazdemoguide/pgpool
      tag: 4.3.3-debian-11-r28

    replicaCount: 1
    resources:
      requests:
        memory: 256Mi
        cpu: 5m
      limits:
        memory: 512Mi
        cpu: 1500m
        
    childLifeTime: 3600
    containerSecurityContext:
      runAsNonRoot: true
    
    adminUsername: haservices
    adminPassword: haservicespass

